### ISSUE TITLE
Compilation of ch32v003_uart.h fails with UART_PINS_TXPD0_RXPD1

### ISSUE THREAD

**Issue by 89Mods** [hexeguitar/ch32v003fun_libs#1]
I have the following configuration:

```
#define FUNCONF_UART_PRINTF_BAUD 31250
#define UART_PINS_TXPD0_RXPD1
#define UART_MODE_RX
#define CH32V003_UART_IMPLEMENTATION
```

which causes this error when running `make`:

```
../ch32v003fun_libs/ch32v003_uart.h: In function 'UART_init':
../ch32v003fun_libs/ch32v003_uart.h:165:32: error: 'UART_PIN_RX' undeclared (first use in this function); did you mean 'UART_PIN_SCL'?
  165 |  UART_PORT->CFGLR &= ~(0xf<<(4*UART_PIN_RX));
      |                                ^~~~~~~~~~~
      |                                UART_PIN_SCL
```

Other configurations, such as `UART_PINS_TXPC0_RXPC1` compile without issue.

**Comment by hexeguitar** [comment]
Copy/paste typo. Thanks for pointing out. Already fixed.
Be careful with that configuration, though. It disables the SWIO pin, the debug access will be lost. 
I'd add a 100-200ms delay at startup before initializing the library to give the programmer enough time to grab the control.
