### ISSUE TITLE
Small copy/paste oversight in constant name

### ISSUE THREAD

**Issue by romain145** [hexeguitar/ch32v003fun_libs#2]
https://github.com/hexeguitar/ch32v003fun_libs/blob/2aa0bdfc2d3c6cec9c8106f13eb466711c347218/ch32v003_uart.h#L141

This should read

`uint8_t uart_rx_bf[UART_RX_BF_SIZE]; // receive buffer`

**Comment by hexeguitar** [comment]
Fixed. Thank you!
